### ISSUE TITLE
GitHub pages doesn't like typedoc

### ISSUE THREAD

**Issue by mozi-h** [wintergatan-community/vmmx-schema#15]
I've built the typedocs into `docs` and told GitHub Pages to load them. It doesn't like any page but the index, for some reason.  
Help appreciated; I'll look into this more too (but will go to sleep for now :D)

**Comment by micahswitzer** [comment]
You need to put an empty file named `.nojekyll` in the docs directory. It took me ages to figure that out when I tried setting up the docks for my fork.

**Comment by mozi-h** [comment]
Did that; still doesn't like the docs
Good catch though I remember reading the GitHub pages documentation like "never going to need `.nojekyll`"

**Comment by micahswitzer** [comment]
It looks like it's working to me.

**Comment by mozi-h** [comment]
Ah yes. It just needed a few more minutes (or days ^^)
Thanks!
